  defaults: &defaults
    computer_path: "/home/ilia/distr/aries_diser"
    filename: 'al_vac_500_medium.txt'
    needed: ['exp', 'title']
    server: 'http://fsla0.ksan.ru/api.php'
    token: '123456'

  development:
    <<: *defaults

  test:
    <<: *defaults

  production:
    <<: *defaults

